language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: RQH6KzxjBQWacdhYT80XGO5EnQ6FgYyuz80yvLAKBaW0ZNKz17MPPQsyMI47MtdrV4aIU1nv20PMc9DrKR0fZ3D9SIwS5i+oHdW1GB4AzBR1dG+woJHnTvdVlAHbkUKi6h4YJGYs6exgC6DR/udoXIR71J9zPI6Ro9KcPob89/JzHymR7aluCwPq2lMJJawu//Y6ppYfnOE6Bao8HQ7kbXrMXvOIXJmvBvuWrAlnPjs3t3bl8/yPdu2veFn3g9R80kJr5yeIneri24lSE7vASNj9dYnioAkDe4ahrfEV32bBClYTh66feXTcCrb0o4vlj3XPLY1BOKU3h8MY6Zof/uvMUqim09yj0KznXo/Z1Hd57fgR5niIYATtE28J09p70rK8kqOstTOUNf59ilDaxbbC9p91dJ77zKQ3zbtSsilEiLcAgqoI8eee59+2LrIEEFefvvkZju4Isz2wpnGVoXBQF4bRI4UOG+CZnJq5ZctA7lPPfTCv0qpwrXIIwStldvrPyFiw4ummDTmlTVwxptnZg7sI+e1eX8833cyg4Qfz3HNtsTONfZeXxtpUCzPqYpekoqJ8YOaw9rFMfNgi80qW/6cv1E/rxkIwcnidBdNBycDHhPfwRa/1Q5iUndROPxj+o2zAsEWwQZMjzSr72UyBF1LolX051i6GSa2uocY=
  app: CapstoneNodeContactApp
  on:
    repo: surbhiguptasai/CapstoneNode
